name: kharcha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  flutter_sms_inbox: ^1.0.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
  fonts:
    - family: FunnelDisplay
      fonts:
        - asset: assets/font/FunnelDisplay-Light.ttf
          weight: 300
        - asset: assets/font/FunnelDisplay-Regular.ttf
          weight: 400
        - asset: assets/font/FunnelDisplay-Medium.ttf
          weight: 500
        - asset: assets/font/FunnelDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/font/FunnelDisplay-Bold.ttf
          weight: 700
        - asset: assets/font/FunnelDisplay-ExtraBold.ttf
          weight: 800
