name: kharcha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
  fonts:
    - family: FunnelDisplay
      fonts:
        - asset: assets/font/FunnelDisplay-Light.ttf
          weight: 300
        - asset: assets/font/FunnelDisplay-Regular.ttf
          weight: 400
        - asset: assets/font/FunnelDisplay-Medium.ttf
          weight: 500
        - asset: assets/font/FunnelDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/font/FunnelDisplay-Bold.ttf
          weight: 700
        - asset: assets/font/FunnelDisplay-ExtraBold.ttf
          weight: 800
