// Mocks generated by Mockito 5.4.6 from annotations
// in kharcha/test/utils/background/flutter_startup_reader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/foundation.dart' as _i3;
import 'package:kharcha/utils/drive/drive_backup_service.dart' as _i2;
import 'package:kharcha/utils/drive/transaction_repository.dart' as _i6;
import 'package:kharcha/utils/sms/sms_transaction.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDriveBackupResult_0 extends _i1.SmartFake
    implements _i2.DriveBackupResult {
  _FakeDriveBackupResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_1<T> extends _i1.SmartFake
    implements _i3.ValueNotifier<T> {
  _FakeValueNotifier_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DriveBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveBackupService extends _i1.Mock
    implements _i2.DriveBackupService {
  MockDriveBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DriveBackupResult> backupTransactionsToDrive(
    List<_i5.SmsTransaction>? transactions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#backupTransactionsToDrive, [transactions]),
            returnValue: _i4.Future<_i2.DriveBackupResult>.value(
              _FakeDriveBackupResult_0(
                this,
                Invocation.method(#backupTransactionsToDrive, [transactions]),
              ),
            ),
          )
          as _i4.Future<_i2.DriveBackupResult>);

  @override
  _i4.Future<_i2.DriveBackupResult> updateTransactionInDrive({
    required _i5.SmsTransaction? original,
    required _i5.SmsTransaction? updated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransactionInDrive, [], {
              #original: original,
              #updated: updated,
            }),
            returnValue: _i4.Future<_i2.DriveBackupResult>.value(
              _FakeDriveBackupResult_0(
                this,
                Invocation.method(#updateTransactionInDrive, [], {
                  #original: original,
                  #updated: updated,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.DriveBackupResult>);

  @override
  _i4.Future<_i2.DriveBackupResult> deleteTransactionFromDrive({
    required _i5.SmsTransaction? transaction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransactionFromDrive, [], {
              #transaction: transaction,
            }),
            returnValue: _i4.Future<_i2.DriveBackupResult>.value(
              _FakeDriveBackupResult_0(
                this,
                Invocation.method(#deleteTransactionFromDrive, [], {
                  #transaction: transaction,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.DriveBackupResult>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i6.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ValueNotifier<List<_i5.SmsTransaction>> get transactionsNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#transactionsNotifier),
            returnValue: _FakeValueNotifier_1<List<_i5.SmsTransaction>>(
              this,
              Invocation.getter(#transactionsNotifier),
            ),
          )
          as _i3.ValueNotifier<List<_i5.SmsTransaction>>);

  @override
  _i3.ValueNotifier<bool> get isLoadingNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingNotifier),
            returnValue: _FakeValueNotifier_1<bool>(
              this,
              Invocation.getter(#isLoadingNotifier),
            ),
          )
          as _i3.ValueNotifier<bool>);

  @override
  List<_i5.SmsTransaction> get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: <_i5.SmsTransaction>[],
          )
          as List<_i5.SmsTransaction>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasLoaded =>
      (super.noSuchMethod(Invocation.getter(#hasLoaded), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadTransactions({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadTransactions, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void updateTransactions(List<_i5.SmsTransaction>? updated) =>
      super.noSuchMethod(
        Invocation.method(#updateTransactions, [updated]),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}
